name: Build APK for React Native Android

on:
  push:
    branches:
      - main  # Set the branch you want to trigger the workflow
  pull_request:
    branches:
      - main  # Trigger when PRs are created to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # The environment where the build will run (Linux, macOS, or Windows)

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # Checkout the repository code

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify your Node.js version

      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        run: |
          npm install  # Or use yarn if you prefer

      - name: Set up Android SDK
        run: |
          echo "sdk.dir=$HOME/Android/Sdk" > $GITHUB_WORKSPACE/android/local.properties
          sudo apt-get install -y openjdk-11-jdk  # Install Java if needed

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleRelease  # Build the APK in release mode

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
